apiVersion: apps/v1
kind: Deployment
metadata:
  name: pledgemanager-local-campaigns
  namespace: dapr-pledgemanager
  labels:
    app: pledgemanager-local-campaigns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pledgemanager-local-campaigns
  template:
    metadata:
      labels:
        app: pledgemanager-local-campaigns
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pledgemanager-local-campaigns"
        dapr.io/app-port: "6000"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: pledgemanager-local-campaigns
        image: pledgemanager-be-campaigns:1.0
        ports:
        - containerPort: 6000


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pledgemanager-local-campaigns
  name: pledgemanager-local-campaigns
  namespace: dapr-pledgemanager
spec:
  type: LoadBalancer
  ports:
  - name: "data"
    port: 6000
    targetPort: 6000
  selector:
    app: pledgemanager-local-campaigns
