apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pledgemanager-local-statestore
  namespace: dapr-pledgemanager
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
auth:
  secretStore: pledgemanager-secrets
scopes:
  - pledgemanager-campaigns
  - pledgemanager-users