# Azure Container Apps does not currently support DAPR Component Schema. 
# So this file uses possible schema that works!! 
# components.yaml for Azure Blob storage component
- name: statestore
  type: state.azure.blobstorage
  version: v1
  metadata:
  # Note that in a production scenario, account keys and secrets 
  # should be securely stored. For more information, see
  # https://docs.dapr.io/operations/components/component-secrets
  - name: accountName
    value: storemanagerstorage
  - name: accountKey
    value: account-key-goes-here
  - name: containerName
    value: statenactors
