# Azure Container Apps does not currently support DAPR Component Schema. 
# So this file uses possible schema that works!! 
# components.yaml for Azure Redis store component
- name: statestore
  type: state.redis
  version: v1
  metadata:
  # Note that in a production scenario, account keys and secrets 
  # should be securely stored. For more information, see
  # https://docs.dapr.io/operations/components/component-secrets
  - name: redisHost
    value: storemanager-6.redis.cache.windows.net:6379
  - name: redisPassword
    value: "Xf3gsmvLpS1PVPK8DDAe5OZnXRQvlXfwiAzCaDJYlmg="
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
# components.yaml for Azure Redis pubsub component
- name: pubsub
  type: pubsub.redis
  version: v1
  metadata:
  # Note that in a production scenario, account keys and secrets 
  # should be securely stored. For more information, see
  # https://docs.dapr.io/operations/components/component-secrets
  - name: redisHost
    value: storemanager-6.redis.cache.windows.net:6379
  - name: redisPassword
    value: "Xf3gsmvLpS1PVPK8DDAe5OZnXRQvlXfwiAzCaDJYlmg="
  - name: consumerID
    value: "myGroup"
  - name: enableTLS
    value: "false"