apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-pledgemanager
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    secretKeyRef:
      name: state.redisPassword
      key: state.redisPassword
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
auth:
  secretStore: pledgemanager-secrets
scopes:
  - pledgemanagerprocessors
  - pledgemanagerapi
