name: Publish & deploy pledge-manager to Azure Container Apps 

#Requires Azure Service Prinicipal 
#az ad sp create-for-rbac --name "githubaction" --role contributor --scopes /subscriptions/<your-sub_id> --sdk-auth

on:
  # push:
  #   branches:
  #     - main
  
  workflow_dispatch:

jobs:
  publish:
    name: Dockerize and publish
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: khaledhikmat
      IMAGE_TAG: latest #${{ github.run_number }} 
    
    steps:

      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Build images
        run: |
          docker image build ./src --file ./src/Dockerfile-backend-campaigns --tag $DOCKER_REPOSITORY/pledgemanager-be-campaigns:$IMAGE_TAG 
          docker image build ./src --file ./src/Dockerfile-frontend-functions --tag $DOCKER_REPOSITORY/pledgemanager-fe-functions:$IMAGE_TAG 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Push images to Docker hub
        run: |
          docker push $DOCKER_REPOSITORY/pledgemanager-be-campaigns:$IMAGE_TAG
          docker push $DOCKER_REPOSITORY/pledgemanager-fe-functions:$IMAGE_TAG

  deploy:
    needs: publish
    name: Depoy Azure resources
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP }}      

      - name: Load Azure CLI and deploy using bicep 
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create \
            --location eastus \
            --template-file ./src/deploy/aca/bicep/main.bicep \
            --parameters ./src/deploy/aca/bicep/dev-env-params.json      
